main_page_url = "https://qa-stellarburgers.education-services.ru/"
login_page_url = "https://qa-stellarburgers.education-services.ru/login"
forgot_pass_page_url = "https://qa-stellarburgers.education-services.ru/forgot-password"
reset_pass_page_url = "https://qa-stellarburgers.education-services.ru/reset-password"
profile_page_url = "https://qa-stellarburgers.education-services.ru/account/profile"
order_history_page_url = "https://qa-stellarburgers.education-services.ru/account/order-history"
order_list_page_url = "https://qa-stellarburgers.education-services.ru/feed"
